### ISSUE TITLE
Forgot to enable gcp-support group in 0-bootstrap phase

### ISSUE THREAD

**Issue by vlatitude** [GoogleCloudPlatform/cloud-foundation-fabric#1840] opened 2023-11-02 17:56 UTC
Hello, after making the change to enable the gcp-support group, when I run terraform apply for the second time, it tries to create existing resources and does not create the gcp-support group.

**Comment by ludoo** [comment] 2023-11-02 19:09
We don't create groups. It's not clear what the problem is on our side. Closing but feel free to reopen and provide a way to understand what's happening, and to reproduce.

**Closed by ludoo** 2023-11-02 19:09 UTC
