### ISSUE TITLE
Removing secure tags doesn't remove tags

### ISSUE THREAD

**Issue by Sekyrovat** [GoogleCloudPlatform/cloud-foundation-fabric#2258] opened 2024-05-07 16:30 UTC
**Describe the bug**
While using the module [compute-vm](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/compute-vm), creating a VM with the `tag_bindings_firewall` has 2 issues that I've encountered:

1. If the VM is created at first with no tags adding the binding and defining the tag forces a recreation.
2. Perhaps more importantly, and my current focus, if a VM is created with given tags and they are then removed, the tags don't seem to be properly removed from the VM.

**Environment**
```
output from `terraform -version`
Terraform v1.8.2
```

**To Reproduce**
Create a given VM with Secure tags using the `compute-vm` module. E.G:
```
module "commonSvcs_service_instance" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/compute-vm"
  project_id = var.serviceProj
  name       = "backend1"
  zone       = "${var.usc1}-a"

  instance_type = var.vm_size

  network_interfaces = [{
    network            = module.commonVpc.self_link
    nat                = false
    subnetwork         = module.common.subnets["${var.usc1}/${local.snet1}"].id
    subnetwork_project = var.commonHost
  }]

  boot_disk = {
    initialize_params = {
      image = var.os_pick
    }
  }
  attached_disks = [{
    name = "disk-1"
    size = 10
  }]

  service_account = {
    email  = "${var.serviceProjComputeSa}"
    scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }

  tag_bindings_firewall = {
     "tagKeys/281484905523145" = "tagValues/281483343838467"
  }
}
```

Then commenting out the given tag in `tag_bindings_firewall` should remove the binding.
```
module "commonSvcs_service_instance" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/compute-vm"
  project_id = var.serviceProj
  name       = "backend1"
  zone       = "${var.usc1}-a"

  instance_type = var.vm_size

  network_interfaces = [{
    network            = module.commonVpc.self_link
    nat                = false
    subnetwork         = module.common.subnets["${var.usc1}/${local.snet1}"].id
    subnetwork_project = var.commonHost
  }]

  boot_disk = {
    initialize_params = {
      image = var.os_pick
    }
  }
  attached_disks = [{
    name = "disk-1"
    size = 10
  }]

  service_account = {
    email  = "${var.serviceProjComputeSa}"
    scopes = ["https://www.googleapis.com/auth/cloud-platform"]
  }

  tag_bindings_firewall = {
     # "tagKeys/281484905523145" = "tagValues/281483343838467"
  }
}
```

**Expected behavior**

Tag should be removed and no longer in use in the VM.

**Result**

The result of commenting out the tag as in the previous example yields:

```
Terraform will perform the following actions:

  # module.commonSvcs_service_instance.google_compute_instance.default[0] will be updated in-place
  ~ resource "google_compute_instance" "default" {
        id                        = "projects/SVC_PROJ/zones/us-central1-a/instances/backend1"
        name                      = "backend1"
        # (23 unchanged attributes hidden)

      ~ params {
          ~ resource_manager_tags = {
              - "tagKeys/281484905523145" = "tagValues/281483343838467" -> null
            }
        }

        # (6 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Additional context**

Other observations:

- Commenting out the full block does the trick
- If more than 1 tag is bound in this way and only 1 is removed the change seems to work. Commenting all tags seems to lead to the same overall effect where no tag is removed.

**Comment by ludoo** [comment] 2024-05-07 18:46
This is working as intended, tag support in the provider was pretty basic for compute instances, and only worked for tags defined in the instance resource, which as you note trigger recreation if changed.

We'll keep this open while we investigate if support for the tag binding resource (which is separate from instance and would do what you need) has become available.

**Comment by Sekyrovat** [comment] 2024-05-07 19:06
I take it that is due to the use of `resource_manager_tags`, which I do see marked with `In Terraform, this value cannot be updated and changing it will recreate the resource.` in the TF registry. Should we include that note in the readme for this module however?

Noticed that using the resource `google_tags_location_tag_binding` does seem to do the intended trick (correctly deleting all tags). And removing the tags doesn't seem to destroy the resource. However, I guess (not very well versed in TF module deployment) it is not as easy to leverage this type of resource to create the bindings?

**Comment by ludoo** [comment] 2024-05-13 06:47
I remembered I had left a comment in the compute-vm module last time I looked at this

```
# - permadiff in google_tags_location_tag_binding which returns a project
#     number in the tag id even when a project id is set
# - no numeric id exposed from the google_compute_disk resource making it
#     impossible to derive the tag binding parent
# - google_compute_instance.params.resource_manager_tags and
#     google_compute_instance.boot_disk.initialize_params.resource_manager_tags
#     attributes need a map of tag key => tag value, while only the tag value
#     is really needed by the API
```

If you feel strongly about this feature, you might want to make sure all three items above have been addressed in the provider, or open issues there so they will eventually be addressed. :)

I'm closing this for now as there's little to do from the module's side until those are fixed. Thanks for flagging this.

**Closed by ludoo** 2024-05-13 06:47 UTC
Labels: enhancement
